/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import calculator.Calculate;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.text.BadLocationException;
import javax.swing.text.Element;

/**
 *
 * @author DELL
 */
public class ViewCalculator extends javax.swing.JFrame {
    private Calculate program;
    private ImageIcon iconTitle;
    private String preAns;
    private String result;
    private String preFunction;
    private String preExpression;
    
    /**
     * Creates new form ViewCalculator
     */
    public ViewCalculator() {
        this.program = new Calculate();
        this.setIconImage(new ImageIcon("iconTitle.png").getImage());
        initComponents();
        
    }

    public String getPreAns() {
        return preAns;
    }

    public String getPreExpression() {
        return preExpression;
    }

    public String getResult() {
        return result;
    }

    public String getPreFunction() {
        return preFunction;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueFontSize = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputUser = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButtonDivide = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonPow = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButtonMultiple = new javax.swing.JButton();
        tinh = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonOption = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonPreAns = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonClear2 = new javax.swing.JButton();
        jButtonPow2 = new javax.swing.JButton();
        jButtonSQRT = new javax.swing.JButton();
        jButtonMod2 = new javax.swing.JButton();
        jButtonDivide2 = new javax.swing.JButton();
        jButtonPlus2 = new javax.swing.JButton();
        jButtonMinus2 = new javax.swing.JButton();
        jButtonMultiple2 = new javax.swing.JButton();
        tinh2 = new javax.swing.JButton();
        jButtonPreExpression = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jButtonGCD = new javax.swing.JButton();
        jButtonOpen = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButtonLCM = new javax.swing.JButton();
        jButtonReturn = new javax.swing.JButton();
        jButtonX = new javax.swing.JButton();
        jButtonFactorial = new javax.swing.JButton();
        jButtonConvert = new javax.swing.JButton();
        jButtonPreAns2 = new javax.swing.JButton();

        valueFontSize.setValue(5);
        valueFontSize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                valueFontSizeStateChanged(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SUPER CALCULATOR");
        setBackground(new java.awt.Color(0, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frame"); // NOI18N
        setSize(new java.awt.Dimension(560, 911));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputUser.setColumns(20);
        inputUser.setFont(new java.awt.Font("Dialog", 0, 50)); // NOI18N
        inputUser.setRows(4);
        inputUser.setWrapStyleWord(true);
        inputUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputUser.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                inputUserCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(inputUser);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 326));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDivide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonDivide.png"))); // NOI18N
        jButtonDivide.setBorder(null);
        jButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivideActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 130, 111));

        jButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonClear.png"))); // NOI18N
        jButtonClear.setBorder(null);
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 111));

        jButtonPow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonPow.png"))); // NOI18N
        jButtonPow.setBorder(null);
        jButtonPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPowActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPow, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 0, 130, 111));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button9.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 117, 130, 111));

        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonDelete.png"))); // NOI18N
        jButtonDelete.setBorder(null);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 0, 146, 111));

        jButtonPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonPlus.png"))); // NOI18N
        jButtonPlus.setBorder(null);
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 351, 146, 111));

        jButtonMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonMinus.png"))); // NOI18N
        jButtonMinus.setBorder(null);
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 234, 146, 111));

        jButtonMultiple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonMultiple.png"))); // NOI18N
        jButtonMultiple.setBorder(null);
        jButtonMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultipleActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMultiple, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 117, 146, 111));

        tinh.setForeground(new java.awt.Color(0, 255, 255));
        tinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonEqual.png"))); // NOI18N
        tinh.setBorder(null);
        tinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinhActionPerformed(evt);
            }
        });
        jPanel1.add(tinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 468, 146, 111));

        jButton0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button0.png"))); // NOI18N
        jButton0.setBorder(null);
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 468, 130, 111));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button8.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 117, 130, 111));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button6.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 234, 130, 111));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button7.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, 130, 111));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button5.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 234, 130, 111));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button3.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 351, 130, 111));

        jButtonOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonMore.png"))); // NOI18N
        jButtonOption.setBorder(null);
        jButtonOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOptionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 468, 130, 111));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button4.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 234, 130, 111));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button2.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 351, 130, 111));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 351, 130, 111));

        jButtonPreAns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonAns.png"))); // NOI18N
        jButtonPreAns.setBorder(null);
        jButtonPreAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreAnsActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPreAns, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 468, 130, 111));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 332, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonClear2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonClear.png"))); // NOI18N
        jButtonClear2.setBorder(null);
        jButtonClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClear2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonClear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 111));

        jButtonPow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonPow.png"))); // NOI18N
        jButtonPow2.setBorder(null);
        jButtonPow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPow2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonPow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 0, 130, 111));

        jButtonSQRT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sqrt.png"))); // NOI18N
        jButtonSQRT.setBorder(null);
        jButtonSQRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSQRTActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSQRT, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 117, 130, 111));

        jButtonMod2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonPercent.png"))); // NOI18N
        jButtonMod2.setBorder(null);
        jButtonMod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMod2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonMod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 0, 130, 111));

        jButtonDivide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonDivide.png"))); // NOI18N
        jButtonDivide2.setBorder(null);
        jButtonDivide2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivide2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDivide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 0, 146, 111));

        jButtonPlus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonPlus.png"))); // NOI18N
        jButtonPlus2.setBorder(null);
        jButtonPlus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlus2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonPlus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 351, 146, 111));

        jButtonMinus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonMinus.png"))); // NOI18N
        jButtonMinus2.setBorder(null);
        jButtonMinus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinus2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonMinus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 234, 146, 111));

        jButtonMultiple2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonMultiple.png"))); // NOI18N
        jButtonMultiple2.setBorder(null);
        jButtonMultiple2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiple2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonMultiple2, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 117, 146, 111));

        tinh2.setForeground(new java.awt.Color(0, 255, 255));
        tinh2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonEqual.png"))); // NOI18N
        tinh2.setBorder(null);
        tinh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinh2ActionPerformed(evt);
            }
        });
        jPanel3.add(tinh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 468, 146, 111));

        jButtonPreExpression.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pre.png"))); // NOI18N
        jButtonPreExpression.setBorder(null);
        jButtonPreExpression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreExpressionActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonPreExpression, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 468, 130, 111));

        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/).png"))); // NOI18N
        jButtonClose.setBorder(null);
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 117, 130, 111));

        jButtonGCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonGCD.png"))); // NOI18N
        jButtonGCD.setBorder(null);
        jButtonGCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGCDActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonGCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 234, 130, 111));

        jButtonOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/(.png"))); // NOI18N
        jButtonOpen.setBorder(null);
        jButtonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, 130, 111));

        jButtonDot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dot.png"))); // NOI18N
        jButtonDot.setBorder(null);
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 234, 130, 111));

        jButtonLCM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonLCM.png"))); // NOI18N
        jButtonLCM.setBorder(null);
        jButtonLCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLCMActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonLCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 351, 130, 111));

        jButtonReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonMore.png"))); // NOI18N
        jButtonReturn.setBorder(null);
        jButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 468, 130, 111));

        jButtonX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/x.png"))); // NOI18N
        jButtonX.setBorder(null);
        jButtonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 234, 130, 111));

        jButtonFactorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/GiaiThua.png"))); // NOI18N
        jButtonFactorial.setBorder(null);
        jButtonFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFactorialActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFactorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 351, 130, 111));

        jButtonConvert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/convert.png"))); // NOI18N
        jButtonConvert.setBorder(null);
        jButtonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonConvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 351, 130, 111));

        jButtonPreAns2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buttonAns.png"))); // NOI18N
        jButtonPreAns2.setBorder(null);
        jButtonPreAns2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreAns2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonPreAns2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 468, 130, 111));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 332, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valueFontSizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_valueFontSizeStateChanged
        // TODO add your handling code here:
        inputUser.setFont(new Font(inputUser.getFont().getFamily(), Font.PLAIN, (int) valueFontSize.getValue() * 10));
    }//GEN-LAST:event_valueFontSizeStateChanged

    private void inputUserCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_inputUserCaretUpdate
        // TODO add your handling code here:
        
    }//GEN-LAST:event_inputUserCaretUpdate

    private void jButtonOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOptionActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jPanel3.setVisible(true);
        
    }//GEN-LAST:event_jButtonOptionActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        inputUser.append("0");
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        inputUser.append("1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonPreAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreAnsActionPerformed
        // TODO add your handling code here:
        inputUser.append(getPreAns());
    }//GEN-LAST:event_jButtonPreAnsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        inputUser.append("2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        inputUser.append("3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        inputUser.append("4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        inputUser.append("5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        inputUser.append("6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        inputUser.append("7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        inputUser.append("8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        inputUser.append("9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinhActionPerformed
        // TODO add your handling code here:
        Element paragraph = inputUser.getDocument().getDefaultRootElement();
        int contentCount = paragraph.getElementCount();
        for (int i = 0; i < contentCount; i++) {
            try {
                Element e = paragraph.getElement(i);
                int rangeStart = e.getStartOffset();
                int rangeEnd = e.getEndOffset();
                if(i == contentCount - 1) {
                    this.preExpression = inputUser.getText(rangeStart, rangeEnd - rangeStart - 1);
                    this.result = program.tinh(getPreExpression()); //tái sử dụng biến lịch sử
                    this.preAns = result;
                    inputUser.append(" =\n=> " + getResult() + "\n");
                }
            } catch (BadLocationException ex) {
                Logger.getLogger(ViewCalculator.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception e) {
                
            }
        }
    }//GEN-LAST:event_tinhActionPerformed

    private void jButtonMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultipleActionPerformed
        // TODO add your handling code here:
        inputUser.append("*");
    }//GEN-LAST:event_jButtonMultipleActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        // TODO add your handling code here:
        inputUser.append("-");
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        // TODO add your handling code here:
        inputUser.append("+");
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        try {
            String str = inputUser.getText();
            inputUser.setText("");
            str = str.substring(0, str.length() - 1);
            inputUser.append(str);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPowActionPerformed
        // TODO add your handling code here:
        inputUser.append("^");
    }//GEN-LAST:event_jButtonPowActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        inputUser.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClear2ActionPerformed
        // TODO add your handling code here:
        inputUser.setText("");
    }//GEN-LAST:event_jButtonClear2ActionPerformed

    private void jButtonPow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPow2ActionPerformed
        // TODO add your handling code here:
        inputUser.append("^");
    }//GEN-LAST:event_jButtonPow2ActionPerformed

    private void jButtonSQRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSQRTActionPerformed
        // TODO add your handling code here:
        inputUser.append("√(");
    }//GEN-LAST:event_jButtonSQRTActionPerformed

    private void jButtonDivide2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivide2ActionPerformed
        // TODO add your handling code here:
        inputUser.append("/");
    }//GEN-LAST:event_jButtonDivide2ActionPerformed

    private void jButtonPlus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlus2ActionPerformed
        // TODO add your handling code here:
        inputUser.append("+");
    }//GEN-LAST:event_jButtonPlus2ActionPerformed

    private void jButtonMinus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinus2ActionPerformed
        // TODO add your handling code here:
        inputUser.append("-");
    }//GEN-LAST:event_jButtonMinus2ActionPerformed

    private void jButtonMultiple2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiple2ActionPerformed
        // TODO add your handling code here:
        inputUser.append("*");
    }//GEN-LAST:event_jButtonMultiple2ActionPerformed

    private void tinh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinh2ActionPerformed
        // TODO add your handling code here:
        Element paragraph = inputUser.getDocument().getDefaultRootElement();
        int contentCount = paragraph.getElementCount();
        for (int i = 0; i < contentCount; i++) {
            System.out.println(i);
            try {
                Element e = paragraph.getElement(i);
                int rangeStart = e.getStartOffset();
                int rangeEnd = e.getEndOffset();
                if(i == contentCount - 1) {
                    this.preExpression = inputUser.getText(rangeStart, rangeEnd - rangeStart - 1);
                    this.result = program.tinh(getPreExpression()); //tái sử dụng biến lịch sử
                    this.preAns = result;
                    inputUser.append(" =\n=> " + getResult() + "\n");
                }
            } catch (BadLocationException ex) {
                Logger.getLogger(ViewCalculator.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tinh2ActionPerformed

    private void jButtonPreExpressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreExpressionActionPerformed
        // TODO add your handling code here:
        inputUser.append(getPreExpression());
    }//GEN-LAST:event_jButtonPreExpressionActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        inputUser.append(")");
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonGCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGCDActionPerformed
        // TODO add your handling code here:
        inputUser.append("GCD(");
    }//GEN-LAST:event_jButtonGCDActionPerformed

    private void jButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenActionPerformed
        // TODO add your handling code here:
        inputUser.append("(");
    }//GEN-LAST:event_jButtonOpenActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        // TODO add your handling code here:
        inputUser.append(".");
    }//GEN-LAST:event_jButtonDotActionPerformed

    private void jButtonLCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLCMActionPerformed
        // TODO add your handling code here:
        inputUser.append("LCM(");
    }//GEN-LAST:event_jButtonLCMActionPerformed

    private void jButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jButtonReturnActionPerformed

    private void jButtonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXActionPerformed
        // TODO add your handling code here:
        inputUser.append("x");
    }//GEN-LAST:event_jButtonXActionPerformed

    private void jButtonFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFactorialActionPerformed
        // TODO add your handling code here:
        inputUser.append("!");
    }//GEN-LAST:event_jButtonFactorialActionPerformed

    private void jButtonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertActionPerformed
        // TODO add your handling code here:
        inputUser.append("$(");
    }//GEN-LAST:event_jButtonConvertActionPerformed

    private void jButtonPreAns2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreAns2ActionPerformed
        // TODO add your handling code here:
        inputUser.append(getPreAns());
    }//GEN-LAST:event_jButtonPreAns2ActionPerformed

    private void jButtonMod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMod2ActionPerformed
        // TODO add your handling code here:
        inputUser.append("%");
    }//GEN-LAST:event_jButtonMod2ActionPerformed

    private void jButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivideActionPerformed
        // TODO add your handling code here:
        inputUser.append("/");
    }//GEN-LAST:event_jButtonDivideActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea inputUser;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonClear2;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonConvert;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDivide;
    private javax.swing.JButton jButtonDivide2;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonFactorial;
    private javax.swing.JButton jButtonGCD;
    private javax.swing.JButton jButtonLCM;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMinus2;
    private javax.swing.JButton jButtonMod2;
    private javax.swing.JButton jButtonMultiple;
    private javax.swing.JButton jButtonMultiple2;
    private javax.swing.JButton jButtonOpen;
    private javax.swing.JButton jButtonOption;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonPlus2;
    private javax.swing.JButton jButtonPow;
    private javax.swing.JButton jButtonPow2;
    private javax.swing.JButton jButtonPreAns;
    private javax.swing.JButton jButtonPreAns2;
    private javax.swing.JButton jButtonPreExpression;
    private javax.swing.JButton jButtonReturn;
    private javax.swing.JButton jButtonSQRT;
    private javax.swing.JButton jButtonX;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tinh;
    private javax.swing.JButton tinh2;
    private javax.swing.JSpinner valueFontSize;
    // End of variables declaration//GEN-END:variables
}
